In [1]:
import numpy as np

A = np.array([[1, 0, 0, 0],
              [2, 1, 0, 0],
              [-2, 0, 2, 0],
              [-1, 1, 3, 2]])

det_A = np.linalg.det(A)
print(det_A)


3.999999999999999


In [4]:
import numpy as np

# 데이터셋
X = np.array([[1, 2],
              [3, 3],
              [3, 5],
              [5, 4],
              [5, 6],
              [6, 5],
              [8, 7],
              [9, 8]])

# 데이터셋의 평균 계산
mean_X = np.mean(X, axis=0)

# 데이터셋의 중심을 원점으로 이동
X_centered = X - mean_X

# 공분산 행렬 계산
covariance_matrix = np.cov(X_centered.T)

# 공분산 행렬의 고유값과 고유벡터 계산
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

# 고유값이 큰 순서대로 고유벡터 정렬
sorted_indices = np.argsort(eigenvalues)[::-1]
principal_components = eigenvectors[:, sorted_indices]

print("Principal Components:")
print(principal_components)


Principal Components:
[[ 0.80864711 -0.58829402]
 [ 0.58829402  0.80864711]]


In [8]:
import numpy as np

# 주어진 행렬 A#
A = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])

# 고유값과 고유벡터 계산
eigenvalues, eigenvectors = np.linalg.eig(A)

# 결과 출력
print("고유값:", eigenvalues)
print("고유벡터:\n", eigenvectors)


고유값: [3.41421356 2.         0.58578644]
고유벡터:
 [[-5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01  4.05405432e-16  7.07106781e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01]]
