In [2]:
import numpy as np

In [3]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [8]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([5,4,3])

x1_new = x1[:,np.newaxis] #column_vector로 바꿔준다.
print(x1.shape) #1차원 벡터
print(x1_new.shape) #2차원 벡터


(5,)
(5, 1)


In [9]:
print(x1_new + x2)

[[ 6  5  4]
 [ 7  6  5]
 [ 8  7  6]
 [ 9  8  7]
 [10  9  8]]
